/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Inspection: typeof import('./src/components/Inspection.vue')['default']
    InspectionList: typeof import('./src/components/InspectionList.vue')['default']
    InspectionOverview: typeof import('./src/components/InspectionOverview.vue')['default']
    InspectionTable: typeof import('./src/components/InspectionTable.vue')['default']
    OrderBy: typeof import('./src/components/OrderBy.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UploadReportDialog: typeof import('./src/components/UploadReportDialog.vue')['default']
    VehicleInformation: typeof import('./src/components/VehicleInformation.vue')['default']
    Violations: typeof import('./src/components/Violations.vue')['default']
  }
}
